    - name: Create docker folder and subfolders
      become: true
      file:
        path: "{{ docker_root_folder }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - appdata
        - custom
        - logs
        - scripts
        - secrets
        - shared