####
- name: first time configuration
  hosts: localhost
  become: true
  tags: setup
  roles:
    - bootstrap
#######  docker configuration 
- name: install docker , docker compose , pip for using with ansible 
  hosts: all
  become: false
  roles: 
    #- geerlingguy.docker
    #- geerlingguy.pip
    - docker