# Bootstrap Role Variables
bootstrap_install_list:
  - git
  - htop
  - sudo
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - ntp
  - zip
  - unzip
  - apt-transport-https
  - net-tools
  - ncdu
  - apache2-utils
  - nano
  - ufw
  - neofetch
  - python3-pip
  - qemu-guest-agent
  - aptitude
  - acl
  
bootstrap_admin_user: autoadmin

# Docker Role Variables
docker_root_folder: "/home/{{ bootstrap_admin_user }}/docker"
PUID: 1000
PGID: 1000
TZ: "Asia/Jerusalem"
USERDIR: "/home/{{ bootstrap_admin_user }}"
DOCKERDIR: "/home/{{ bootstrap_admin_user }}/docker"
DATADIR: "/media/storage"
HOSTNAME: "udms"

# Traefik Role Variables
traefik_version: v2.5.4
traefik_data_folder: "/home/{{ bootstrap_admin_user }}/traefik"
DOMAINNAME_1: "{{ vault_DOMAINNAME_1 }}"
LOCAL_IPS: "127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,192.168.14.0/12"
CLOUDFLARE_IPS: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
http_username: "{{ vault_http_username }}"
http_password: "{{ vault_http_password }}"
cloudflare_dns_api_token: "{{ vault_cloudflare_dns_api_token }}"
docker_privileged_mode: false # Set to true to run traefik in privileged mode true\vm  false\container
use_staging: false  # Set to true to use staging certificates
reset_acme: true  # Set to true to reset the acme.json file
