############################### create docker networks 
- name: Create socket_proxy network
  community.docker.docker_network:
    name: socket_proxy
    driver: bridge
    ipam_config:
      - subnet: 192.168.91.0/24
- name: Create t2_proxy network
  community.docker.docker_network:
    name: t2_proxy
    driver: bridge
    ipam_config:
      - subnet: 192.168.90.0/24
################################ core services
- name: Ensure Docker Socket Proxy container is running
  community.docker.docker_container:
    name: socket-proxy
    image: tecnativa/docker-socket-proxy
    security_opts:
      - no-new-privileges:true
    restart_policy: unless-stopped
    networks:
      - name: socket_proxy
    ports:
      - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      LOG_LEVEL: "info"
      EVENTS: "1"
      PING: "1"
      VERSION: "1"
      AUTH: "0"
      SECRETS: "0"
      POST: "1"
      BUILD: "0"
      COMMIT: "0"
      CONFIGS: "0"
      CONTAINERS: "1"
      DISTRIBUTION: "0"
      EXEC: "0"
      IMAGES: "1"
      INFO: "1"
      NETWORKS: "1"
      NODES: "0"
      PLUGINS: "0"
      SERVICES: "1"
      SESSION: "0"
      SWARM: "0"
      SYSTEM: "0"
      TASKS: "1"
      VOLUMES: "1"